version: "3"
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app

  mongo-db:
    image: mongo
    ports:
      - 27017:27017
